#服务注册中心端口号
server:
   port: 9001
spring:
   application:
        name: configClient

#服务注册中心实例的主机名
eureka:
#是否向服务注册中心注册自己
   instance:
   # 心跳时间，即服务续约间隔时间（缺省为30s）
     lease-renewal-interval-in-seconds: 5
     # 发呆时间，即服务续约到期时间（缺省为90s）
     lease-expiration-duration-in-seconds: 15
   client:
      healthcheck:
         enabled: true
#服务注册中心的配置内容，指定服务注册中心的位置
      serviceUrl:
         defaultZone: http://localhost:8080/eureka/
