#服务注册中心端口号 default
server:
   port: 8080
spring:
   application:
        name: eurekaServer

#服务注册中心实例的主机名
eureka:
   instance:
      hostname: localhost
   server:
   #关闭自我保护
      enableSelfPreservation: false
      # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
      eviction-interval-timer-in-ms: 1000
#是否向服务注册中心注册自己
   client:
      register-with-eureka: false
#是否检索服务
      fetch-registry: false
#服务注册中心的配置内容，指定服务注册中心的位置
      serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
